site_name: MIGScripts
nav:
    - Home: index.md
    - Exchange: 
      - Validate-AdaptiveScopesOPATHQuery.ps1: exo/validate-adaptivescopesopathquery.md
    #  - Get-MailboxRetentionInfo: get-mailboxretentioninfo.md
    #  - Get-ELCLastSuccessTimestamp: get-elclastsuccesstimestamp.md
    #- SharePoint/OneDrive:
    #  - Adaptive Scopes Property Bag: adaptivescopes-propertybag.md
    - ⚠️ Submit an issue: https://github.com/brenle/MIGScripts/issues
theme: readthedocs
